version: '3'
services:
  registry:
    image: aida/teastore-registry
    expose:
      - "8443"
    ports:
      - "8442:8443"
  db:
    image: descartesresearch/teastore-db
    expose:
      - "3306"
    ports:
      - "3306:3306"
  persistence:
    image: aida/teastore-persistence
    expose:
      - "8443"
    ports:
      - "8444:8443"
    environment:
      HOST_NAME: "aida.bxmina.com"
      REGISTRY_HOST: "aida.bxmina.com"
      REGISTRY_PORT: "8442"
      DB_HOST: "aida.bxmina.com"
      DB_PORT: "3306"
      SERVICE_PORT: "8444"
  auth:
    image: aida/teastore-auth
    expose:
      - "8443"
    ports:
      - "8441:8443"
    environment:
      HOST_NAME: "aida.bxmina.com"
      REGISTRY_HOST: "aida.bxmina.com"
      REGISTRY_PORT: "8442"
      SERVICE_PORT: "8441"
  image:
    image: aida/teastore-image
    expose:
      - "8443"
    ports:
      - "8445:8443"
    environment:
      HOST_NAME: "aida.bxmina.com"
      REGISTRY_HOST: "aida.bxmina.com"
      REGISTRY_PORT: "8442"
      SERVICE_PORT: "8445"
  recommender:
    image: aida/teastore-recommender
    expose:
      - "8443"
    ports:
      - "8446:8443"
    environment:
      HOST_NAME: "aida.bxmina.com"
      REGISTRY_HOST: "aida.bxmina.com"
      REGISTRY_PORT: "8442"
      SERVICE_PORT: "8446"
  webui:
    image: aida/teastore-webui
    expose:
      - "8443"
    environment:
      HOST_NAME: "aida.bxmina.com"
      REGISTRY_HOST: "aida.bxmina.com"
      REGISTRY_PORT: "8442"
    ports:
      - "8443:8443"