name: Development

on:
  push:
    branches:
      - development

jobs:
  test:
    name: Test all TeaStore variants
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: mvn clean install
      - run: cd tools/ && ./build_docker.sh && cd .. # build docker images locally
      # test default (HTTP + no Kieker)
      - run: sed -i 's/descartesresearch\///g' examples/docker/docker-compose_default.yaml
      - run: sed -i 's/teastore-db/descartesresearch\/teastore-db/g' examples/docker/docker-compose_default.yaml
      - run: docker-compose -f examples/docker/docker-compose_default.yaml up -d
      - run: echo "Waiting 2 minutes for TeaStore to start." ; sleep 120
      - run: chmod +x tools/test_webui.sh && ./tools/test_webui.sh localhost http 8080
      - run: docker-compose -f examples/docker/docker-compose_default.yaml down
      # test HTTPS
      - run: sed -i 's/descartesresearch\///g' examples/docker/docker-compose_https.yaml
      - run: sed -i 's/teastore-db/descartesresearch\/teastore-db/g' examples/docker/docker-compose_https.yaml
      - run: docker-compose -f examples/docker/docker-compose_https.yaml up -d
      - run: echo "Waiting 2 minutes for TeaStore to start." ; sleep 120
      - run: ./tools/test_webui.sh localhost https 8443
      - run: docker-compose -f examples/docker/docker-compose_https.yaml down
      # test Kieker
      - run: sed -i 's/descartesresearch\///g' examples/docker/docker-compose_kieker.yaml
      - run: sed -i 's/teastore-db/descartesresearch\/teastore-db/g' examples/docker/docker-compose_kieker.yaml
      - run: docker-compose -f examples/docker/docker-compose_rabbitmq.yaml up -d
      - run: echo "Waiting 2 minutes for RabbitMQ to start." ; sleep 120
      - run: docker-compose -f examples/docker/docker-compose_kieker.yaml up -d
      - run: echo "Waiting 2 minutes for TeaStore to start." ; sleep 120
      - run: ./tools/test_webui.sh localhost http 8080
      - run: chmod +x tools/test_kieker.sh && ./tools/test_kieker.sh localhost 5672
      - run: docker-compose -f examples/docker/docker-compose_kieker.yaml down
      - run: docker-compose -f examples/docker/docker-compose_rabbitmq.yaml down

  build:
    name: Build and publish Docker images of TeaStore
    runs-on: ubuntu-latest
    needs: [test]
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: mvn clean install -DskipTests
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-base
          file: utilities/tools.descartes.teastore.dockerbase/Dockerfile
          path: utilities/tools.descartes.teastore.dockerbase
          tags: development
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-recommender
          file: services/tools.descartes.teastore.recommender/Dockerfile
          path: services/tools.descartes.teastore.recommender
          tags: development
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-webui
          file: services/tools.descartes.teastore.webui/Dockerfile
          path: services/tools.descartes.teastore.webui
          tags: development
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-image
          file: services/tools.descartes.teastore.image/Dockerfile
          path: services/tools.descartes.teastore.image
          tags: development
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-auth
          file: services/tools.descartes.teastore.auth/Dockerfile
          path: services/tools.descartes.teastore.auth
          tags: development
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-persistence
          file: services/tools.descartes.teastore.persistence/Dockerfile
          path: services/tools.descartes.teastore.persistence
          tags: development
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-registry
          file: services/tools.descartes.teastore.registry/Dockerfile
          path: services/tools.descartes.teastore.registry
          tags: development
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-db
          file: utilities/tools.descartes.teastore.database/Dockerfile
          path: utilities/tools.descartes.teastore.database
          tags: development
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-kieker-rabbitmq
          file: utilities/tools.descartes.teastore.kieker.rabbitmq/Dockerfile
          path: utilities/tools.descartes.teastore.kieker.rabbitmq
          tags: development
