name: Development

on:
  push:
    branches:
      - development

jobs:
  test-default:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: mvn clean install # TODO: after install, build docker containers and run integration tests
      - run: cd tools/ && ./docker_build.sh -r development-local && cd .. # build docker images locally
      - run: docker-compose -f examples/docker/docker-compose_default.yaml up -d # TODO: also implement for HTTPS and Kieker!
      - run: echo "Waiting 2 minutes for TeaStore to start."; sleep 120
      - run: ./tools/test_default.sh localhost http 8080

  build:
    runs-on: ubuntu-latest
    needs: [test-default]
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: mvn clean install -DskipTests
        
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-base
          file: utilities/tools.descartes.teastore.dockerbase/Dockerfile
          path: utilities/tools.descartes.teastore.dockerbase
          tags: development
          
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-recommender
          file: services/tools.descartes.teastore.recommender/Dockerfile
          path: services/tools.descartes.teastore.recommender
          tags: development
          
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-webui
          file: services/tools.descartes.teastore.webui/Dockerfile
          path: services/tools.descartes.teastore.webui
          tags: development
          
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-image
          file: services/tools.descartes.teastore.image/Dockerfile
          path: services/tools.descartes.teastore.image
          tags: development
              
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-auth
          file: services/tools.descartes.teastore.auth/Dockerfile
          path: services/tools.descartes.teastore.auth
          tags: development
          
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-persistence
          file: services/tools.descartes.teastore.persistence/Dockerfile
          path: services/tools.descartes.teastore.persistence
          tags: development
          
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-registry
          file: services/tools.descartes.teastore.registry/Dockerfile
          path: services/tools.descartes.teastore.registry
          tags: development
          
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-db
          file: utilities/tools.descartes.teastore.database/Dockerfile
          path: utilities/tools.descartes.teastore.database
          tags: development
          
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-kieker-rabbitmq
          file: utilities/tools.descartes.teastore.kieker.rabbitmq/Dockerfile
          path: utilities/tools.descartes.teastore.kieker.rabbitmq
          tags: development
          
