name: DockerHub

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn clean install
  
  
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn clean install -DskipTests
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-base
          file: utilities/tools.descartes.teastore.dockerbase/Dockerfile
          path: utilities/tools.descartes.teastore.dockerbase
          tags: development
