name: Prepare release

on:
  milestone:
    types: [closed]
    
jobs:
  bumpversion:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          ref: 'development'
      - run: echo ::set-env name=VERSION::$(grep -o ".\..\.." <<< "${{ github.event.milestone.title }}")
      - run: sed -i 's/<teastoreversion>.*<\/teastoreversion>/<teastoreversion>${{ env.VERSION }}<\/teastoreversion>/' pom.xml
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Automated version number bump" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: development
