name: Prepare release

on:
  milestone:
    types: [closed]
    
jobs:
  bumpversion:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: grep -o ".\..\.." <<< ${{ github.event.milestone.title }}
      - run: echo ${grep -o ".\..\.." <<< ${{ github.event.milestone.title }}}
