name: Prepare release

on:
  milestone:
    types: [closed]
    
jobs:
  bumpversion:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: version=$(grep -o ".\..\.." <<< "${{ github.event.milestone.title }}")
      - run: echo ${{version}}
        with:
           version: grep -o ".\..\.." <<< "test 1.2.2"
