name: Prepare release

on:
  milestone:
    types: [closed]
    
jobs:
  bumpversion:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: grep -o ".\..\.." <<< "${{ github.event.milestone.title }}"
      - run: sed -i 's/<teastoreversion>.*<\/teastoreversion>/<teastoreversion>${grep -o ".\..\.." <<< "${{ github.event.milestone.title }}"}<\/teastoreversion>/' pom.xml
      - run: cat pom.xml
