name: Prepare release

on:
  milestone:
    types: [closed]
    
jobs:
  bumpversion:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: echo $GITHUB_REF
      - run: echo  ${{ github.event }}
