name: Prepare release

on:
  milestone:
    types: [closed]
    
jobs:
  bumpversion:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: echo ::set-env name=VERSION::$(grep -o ".\..\.." <<< "${{ github.event.milestone.title }}")
      - run: sed -i 's/<teastoreversion>.*<\/teastoreversion>/<teastoreversion>$VERSION<\/teastoreversion>/' pom.xml
      - run: cat pom.xml
