name: Prepare release

on:
  milestone:
    types: [closed]
    
jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          ref: 'development'
      - run: echo ::set-env name=VERSION::$(grep -o ".\..\.." <<< "${{ github.event.milestone.title }}")
      - run: sed -i 's/<teastoreversion>.*<\/teastoreversion>/<teastoreversion>${{ env.VERSION }}<\/teastoreversion>/' pom.xml
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Automated version number bump" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: development
          
  pullRequest:
    runs-on: ubuntu-latest
    needs: [bumpVersion]
    steps: 
      - uses: actions/checkout@v2
      - run: echo ::set-env name=VERSION::$(grep -o ".\..\.." <<< "${{ github.event.milestone.title }}")
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "development"                     # If blank, default: triggered branch
          destination_branch: "master"          # If blank, default: master
          pr_title: "Release v${{ env.VERSION }}"
          pr_body: "Auto-generated pull request for release"  # Full markdown support, requires pr_title to be set
          github_token: ${{ secrets.GITHUB_TOKEN }}
